### ISSUE TITLE
subSamleSize hyperparameter missing in the implementation

### ISSUE THREAD

**Issue by ptiagi** [kLabUM/rrcf#37]
While constructing the trees currently all the data points are taken at once for each tree and various trees are constructed using the same set of data points.
As per my understanding of the algorithm, a number(numtrees) of trees of size(subSampleSize) are constructed by taking a random number of data points from all the given data points (where size of the set = subSampleSize). And then for each point in the dataset we calculate the codisp score based on how it changes the shape of each tree and calculate the average of the displacement. 
Is the above described scenario kept for future addition or my understanding of the algorithm is wrong?
Please correct me if I am wrong.

**Comment by mdbartos** [comment]
Thanks for your question.

Ultimately, we leave sampling strategies up to the user. There are advantages and disadvantages to different approaches, and I'm not sure there is a correct approach per se. Our example in the readme uses a very simple FIFO queue, while Guha's original paper uses reservoir sampling. I could post an example of reservoir sampling as well.

I might not be fully understanding your question though. If you have an example that illustrates your question, feel free to create a jupyter notebook in the `/notebooks` directory and submit a pull request.

Thanks,
MDB

**Comment by mdbartos** [comment]
Hi @ptiagi 

I was looking at scikit-learn's implementation of isolation forest, and I think I know what you were saying now.

Were you thinking of something along these lines?:

```python
import numpy as np
import pandas as pd
import rrcf

# Set parameters
np.random.seed(0)
n = 2010
d = 3
num_trees = 100
tree_size = 256

# Generate data
X = np.zeros((n, d))
X[:1000,0] = 5
X[1000:2000,0] = -5
X += 0.01*np.random.randn(*X.shape)

# Construct forest
forest = []
while len(forest) <= num_trees:
    # Select random subsets of points uniformly from point set
    ixs = np.random.choice(n, size=(n // tree_size, tree_size),
                           replace=False)
    # Add sampled trees to forest
    trees = [rrcf.RCTree(X[ix], index_labels=ix) for ix in ixs]
    forest.extend(trees)

# Compute average CoDisp
avg_codisp = pd.Series(0.0, index=np.arange(n))
index = np.zeros(n)
for tree in forest:
    codisp = pd.Series({leaf : tree.codisp(leaf) for leaf in tree.leaves})
    avg_codisp[codisp.index] += codisp
    np.add.at(index, codisp.index.values, 1)
avg_codisp /= index
```

Plotting results:
```python
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import colors

%matplotlib inline

fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111, projection='3d')
sc = ax.scatter(X[:,0], X[:,1], X[:,2], linewidths=0.1, edgecolors='k',
                c=(avg_codisp > avg_codisp.quantile(0.995)).astype(float), cmap='cool')
plt.title('CoDisp above 99th percentile')
plt.tight_layout()
```

![codisp](https://user-images.githubusercontent.com/8175317/50465257-5553c680-0953-11e9-8bdc-34128c1a36b2.png)

**Comment by mdbartos** [comment]
Hi @ptiagi 

I updated the readme with this new example. Thanks.

**Comment by ptiagi** [comment]
Thank you, MDB!
