### ISSUE TITLE
All trees contain same points.

### ISSUE THREAD

**Issue by xphter** [kLabUM/rrcf#60]
I have a question. The new point in stream will be inserted into each trees, so all trees will contain the same points in future. Is it correct?

**Comment by mdbartos** [comment]
If you are inserting the point into every tree, then yes, all trees will contain the point until it is dropped.

You can verify this using `RCTree.find_duplicate`

Note that it is not strictly necessary to insert the point into every tree.

**Comment by xphter** [comment]
Thank you first. Another question ^_^, so the new point should be inserted into a tree randomly, correct?

**Comment by mdbartos** [comment]
Yes, the position of the point in the tree will be random--specifically, it is determined by the insertpoint algorithm shown here: https://klabum.github.io/rrcf/insert-and-delete.html
