### ISSUE TITLE
Package version is not updated in the rrcf.__version__

### ISSUE THREAD

**Issue by TrigonaMinima** [kLabUM/rrcf#73]
When you print `rrcf.__version__`, `0.3.2` is printed whereas, installed version is `0.4.0`

**Comment by mdbartos** [comment]
Whoops. Need to single-source the package version: https://packaging.python.org/guides/single-sourcing-package-version/

tbh, I'm not too crazy about any of these techniques. I will probably go with the setuptools option, as it is already a dependency for this project.

**Comment by mdbartos** [comment]
Greetings,

This should now be fixed in #74
