### ISSUE TITLE
include license in `setup.py`

### ISSUE THREAD

**Issue by whiletruelearn** [kLabUM/rrcf#75]
Hi,

Thanks for maintaining this nice project.  I see that the project is in `MIT License` which is great. Can you also add this to `setup.py` so that it is correctly reflected in `pypi`. Many companies use the meta information available with `pypi` to understand the license of the project , so for `rrcf` it is coming as `unknown` . We just need to add one line to the `setup.py`, Could you please consider updating it. I can send a PR if you would like it that way.

**Comment by mdbartos** [comment]
Thanks for the heads up. If you could submit a PR, that would be great.
