### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by Xiaoshu-Zhao** [kLabUM/rrcf#98]
When we define RCTree, we use the follwing code in `__init__`

```
    else:
        n, d = X.shape
        N = np.ones(n, dtype=np.int)
        I = None
```

However, `np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Please fix it.

**Comment by mdbartos** [comment]
This will be addressed in #95
