### ISSUE TITLE
Unable to install the latest rrcf version 0.4.4

### ISSUE THREAD

**Issue by pkgandhi** [kLabUM/rrcf#99]
Hi there,

I am trying to install the latest version of rrcf but I am unable to. Could someone please help why I won't be able to since it is already available. 

ERROR: Could not find a version that satisfies the requirement rrcf==0.4.4 (from versions: 0.1, 0.2, 0.3, 0.3.2, 0.4, 0.4.1, 0.4.3)
ERROR: No matching distribution found for rrcf==0.4.4

Thanks!

**Comment by mdbartos** [comment]
Greetings, rrcf v0.4.4 should now be uploaded to pypi.
